// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4D2wEIgUs8fW_Vz4-QA0FUJparF9ziB0',
    appId: '1:521433890947:web:706ff9b76bf1947d9c1bb6',
    messagingSenderId: '521433890947',
    projectId: 'farm2home-v2',
    authDomain: 'farm2home-v2.firebaseapp.com',
    storageBucket: 'farm2home-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOz8e8hE5IgQJpdM_Xv7lRhePEFDWLNoA',
    appId: '1:521433890947:android:a0c908bfbf70a4979c1bb6',
    messagingSenderId: '521433890947',
    projectId: 'farm2home-v2',
    storageBucket: 'farm2home-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMtCGamv5OWFWqXdV9cWofN2Yrep29mPo',
    appId: '1:521433890947:ios:f3116ebca928af1e9c1bb6',
    messagingSenderId: '521433890947',
    projectId: 'farm2home-v2',
    storageBucket: 'farm2home-v2.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMtCGamv5OWFWqXdV9cWofN2Yrep29mPo',
    appId: '1:521433890947:ios:f3116ebca928af1e9c1bb6',
    messagingSenderId: '521433890947',
    projectId: 'farm2home-v2',
    storageBucket: 'farm2home-v2.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4D2wEIgUs8fW_Vz4-QA0FUJparF9ziB0',
    appId: '1:521433890947:web:96e687cf13e41ab39c1bb6',
    messagingSenderId: '521433890947',
    projectId: 'farm2home-v2',
    authDomain: 'farm2home-v2.firebaseapp.com',
    storageBucket: 'farm2home-v2.firebasestorage.app',
  );

}